

theme = "catppuccin_mocha"

[editor]
auto-completion=true
# auto-save=true
auto-format=false
bufferline="multiple"
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
# cursor-line = "warning" # show warnings and errors on the cursorline inline
# other-lines = "error"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 300000

[editor.file-picker]
hidden = false # Show dot files

[editor.lsp]
display-messages = true
# display-inlay-hints = true
auto-signature-help=true

[keys.select]
"S-x" = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal]
g = { a = "code_action" } # Maps `ga` to show possible code actions


# Resources
# https://guara.tech/posts/helix_editor_rs_setup/
# https://rushter.com/blog/helix-editor/
